server:
  address: 51.254.36.232
  port: 8085
spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: techstageit@gmail.com
    password: "dbfn mbhq vkqy brfg"
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
  datasource:
    username: appuser
    password: Cavallo3003!
    url: jdbc:postgresql://localhost:5432/backendapp?useSSL=enable
  main:
    allow-bean-definition-overriding: true
    web-application-type: servlet
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true